name: (RELEASE)

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: Release version number
        required: true
        default: '1.0.0.0'
      name:
        description: Name of this release (Default is generated package name)
        required: true
        default: ''
      prerelease:
        description: Prerelease (Y/N)
        required: false
        default: 'N'
      draft:
        description: Draft (Y/N)
        required: false
        default: 'N'
      createReleaseBranch:
        description: Create Release Branch (Y/N)
        required: false
        default: 'N'

permissions:
  contents: write
  pull-requests: write
  actions: read

concurrency: release

defaults:
  run:
    shell: PowerShell

jobs:
  Initialization:
    runs-on: [ windows-latest ]
    outputs:
      type: ${{ steps.ReadSettings.outputs.type }}
      source_branch: ${{ steps.ReadSettings.outputs.source_branch }}
      versions: ${{ steps.ReadSettings.outputs.VersionsJson }}
      environments: ${{ steps.ReadSettings.outputs.EnvironmentsJson }}
      githubRunner: ${{ steps.ReadSettings.outputs.GitHubRunnerJson }}
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        uses: ciellosinc/FSC-PS-Actions/WorkflowInitialize@v1.1
        id: init
        env:
          secrets: ${{ toJson(secrets) }}    

      - name: Read settings
        id: ReadSettings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1
                
      - name: Check for updates to FSC-PS system files
        uses: ciellosinc/FSC-PS-Actions/CheckForUpdates@v1.1
        with:
          type: ${{ steps.ReadSettings.outputs.type }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}
                   
  CreateRelease:
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    needs: [ Initialization ]
    outputs:
      artifact_name: ${{ steps.runpipeline.outputs.PACKAGE_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read settings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1
          
      - name: Read secrets
        uses: ciellosinc/FSC-PS-Actions/ReadSecrets@v1.1
        env:
          secrets: ${{ toJson(secrets) }}    
        with:
          settingsJson: ${{ env.Settings }}
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1.1.1
        with:
          nuget-version: 5.10.x    
      
      - name: Get Env Vars
        run: |
          $settingsJson = '${{ env.Settings }}'
          $settings = $settingsJson | ConvertFrom-Json
          if ($settings) {
            Write-Host "Repo type is: $($settings.type)"
            Add-Content -Path $env:GITHUB_ENV -Value "type=$($settings.type)"
          }
          
      - name: Run pipeline
        uses: ciellosinc/FSC-PS-Actions/RunPipeline@v1.1
        id: runpipeline
        with:
          type: ${{ needs.Initialization.outputs.type}}
          settingsJson: ${{ env.Settings }}
          SecretsJson: ${{ env.RepoSecrets }}

      - name: Publish artifacts  
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: '${{ env.ARTIFACTS_PATH }}'
          
      - name: Publish Release
        id: PublishRelease
        uses: ciellosinc/FSC-PS-Actions/PublishRelease@v1.1   
        with:
          type: ${{ needs.Initialization.outputs.type}}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}
          artifactsPath: '${{ env.ARTIFACTS_PATH }}'

           
  CreateReleaseBranch:
    if: ${{ github.event.inputs.createReleaseBranch=='Y' }}
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    needs: [ Initialization, CreateRelease ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read settings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1

      - name: Create Release Branch
        run: |
          git checkout -b "releases/${{ github.event.inputs.versionNumber }}"
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git commit --allow-empty -m "Release branch ${{ github.event.inputs.versionNumber }}"
          git push origin "releases/${{ github.event.inputs.versionNumber }}"   


  PostProcess:
    if: always()
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    needs: [ Initialization, CreateRelease, CreateReleaseBranch ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read settings
        uses: ciellosinc/FSC-PS-Actions/ReadSettings@v1.1

      - name: Read secrets
        uses: ciellosinc/FSC-PS-Actions/ReadSecrets@v1.1
        env:
          secrets: ${{ toJson(secrets) }}    
        with:
          settingsJson: ${{ env.Settings }}
          
      - name: Finalize the workflow
        id: PostProcess
        uses: ciellosinc/FSC-PS-Actions/WorkflowPostProcess@v1.1
        with:
          remove_current: ${{ needs.Initialization.outputs.environments == '' }}
          settingsJson: ${{ env.Settings }}
          SecretsJson: ${{ env.RepoSecrets }}